jaka_lumi_minicobo_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
jaka_lumi_body:
  kinematics_solver: ""
# jaka_lumi_agv:
#   kinematics_solver: ""