# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - jaka_lumi_body_controller
    - jaka_lumi_minicobo_arm_controller

  jaka_lumi_body_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    # default: true
    joints:
      - l-1
      - l-2
      - l-3
      - l-4
  jaka_lumi_minicobo_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    # default: true
    joints:
      - l-a1
      - l-a2
      - l-a3
      - l-a4
      - l-a5
      - l-a6

trajectory_execution:
  allowed_execution_duration_scaling: 1.5     # or 2.0, to allow 50-100% extra time
  allowed_goal_duration_margin: 2.0          # extra seconds to wait
  allowed_start_tolerance: 0.01  # Increase tolerance to reduce validation delay
  execution_duration_monitoring: false
  moveit_manage_controllers: true
    