# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    jaka_lumi_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    jaka_lumi_minicobo_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # jaka_lumi_agv_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    jaka_lumi_full_robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

jaka_lumi_body_controller:
  ros__parameters:
    joints:
      - l_1
      - l_2
      - l_3
      - l_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
jaka_lumi_minicobo_arm_controller:
  ros__parameters:
    joints:
      - l_a1
      - l_a2
      - l_a3
      - l_a4
      - l_a5
      - l_a6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
# jaka_lumi_agv_controller:
#   ros__parameters:
#     joints:
#       - w_r
#       - w_l
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

jaka_lumi_full_robot_controller:
  ros__parameters:
    joints:
      - l_1
      - l_2
      - l_3
      - l_4
      - l_a1
      - l_a2
      - l_a3
      - l_a4
      - l_a5
      - l_a6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity